TP_vacances/src/Entity/Destination.php
<?php

namespace App\Entity;

use App\Repository\DestinationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DestinationRepository::class)]
class Destination
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $description = null;

    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'Destination')]
    private Collection $users;

    #[ORM\OneToMany(mappedBy: 'Destination', targetEntity: Review::class)]
    private Collection $reviews;

    #[ORM\ManyToOne(inversedBy: 'destinations')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Type $Type = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Image = null;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addDestination($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeDestination($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews->add($review);
            $review->setDestination($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getDestination() === $this) {
                $review->setDestination(null);
            }
        }

        return $this;
    }

    public function getType(): ?Type
    {
        return $this->Type;
    }

    public function setType(?Type $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->Image;
    }

    public function setImage(?string $Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

TP_vacances/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Username = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Review::class)]
    private Collection $Review;

    #[ORM\ManyToMany(targetEntity: Destination::class, inversedBy: 'users')]
    private Collection $Destination;

    public function __construct()
    {
        $this->Review = new ArrayCollection();
        $this->Destination = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername(): ?string
    {
        return $this->Username;
    }

    public function setUsername(string $Username): self
    {
        $this->Username = $Username;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReview(): Collection
    {
        return $this->Review;
    }

    public function addReview(Review $review): self
    {
        if (!$this->Review->contains($review)) {
            $this->Review->add($review);
            $review->setUser($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->Review->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getUser() === $this) {
                $review->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Destination>
     */
    public function getDestination(): Collection
    {
        return $this->Destination;
    }

    public function addDestination(Destination $destination): self
    {
        if (!$this->Destination->contains($destination)) {
            $this->Destination->add($destination);
        }

        return $this;
    }

    public function removeDestination(Destination $destination): self
    {
        $this->Destination->removeElement($destination);

        return $this;
    }
}

TP_vacances/src/Form/DestinationType.php
<?php

namespace App\Form;

use App\Entity\Destination;
use App\Entity\Type;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DestinationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('country')
            ->add('description')
            ->add('type', EntityType::class, [
                'required' => true,
                'label' => 'Choisir un type',
                'class' => Type::class,
                'choice_label' => 'name',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Destination::class,
        ]);
    }
}

TP_vacances/src/Controller/DestinationController.php
<?php

namespace App\Controller;

use App\Entity\Destination;
use App\Entity\Review;
use App\Entity\Type;
use App\Entity\User;
use App\Form\DestinationType;
use App\Form\ReviewType;
use App\Form\TypeType;
use App\Repository\DestinationRepository;
use App\Repository\ReviewRepository;
use App\Repository\TypeRepository;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/destination')]
class DestinationController extends AbstractController
{
    #[Route('/', name: 'app_destination_index', methods: ['GET'])]
    public function index(DestinationRepository $destinationRepository,Request $request, PaginatorInterface $paginator, TypeRepository $typeRepository): Response
    {
        $this->destinationRepository = $destinationRepository;
        $text = '';
        $filter = $request->get('filter');
        $pays = $request->get('pays');
        $filterList = $destinationRepository->findBy(['Type' => $filter, 'country' => $pays]);
        if ($pays == '-- Tous les pays --'){
            $pagination = $paginator->paginate(
                $this->destinationRepository->findBy(['Type' => $filter]),
                $request->query->getInt('page', 1)/*page number*/,
                8/*limit per page*/
            );
        }
        else if($filterList){
                $pagination = $paginator->paginate(
                    $this->destinationRepository->findBy(['Type' => $filter, 'country' => $pays]),
                    $request->query->getInt('page', 1)/*page number*/,
                    8/*limit per page*/
                );
        }
        else{
            if ($pays != null){
                $text = 'Aucun resultat trouver avec votre filtre';
            }
            $pagination = $paginator->paginate(
                $this->destinationRepository->findAll(),
                $request->query->getInt('page', 1)/*page number*/,
                8/*limit per page*/
            );
        }

        $typeList = $typeRepository->findAll();
        return $this->render('destination/index.html.twig', [
            'destination' => $this->destinationRepository->findAll(),
            'pagination' => $pagination,
            'typeList' => $typeList,
            'text' => $text,
        ]);
    }


    #[Route('/new', name: 'app_destination_new', methods: ['GET', 'POST'])]
    public function new(Request $request, DestinationRepository $destinationRepository): Response
    {
        $destination = new Destination();
        $form = $this->createForm(DestinationType::class, $destination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $destinationRepository->save($destination, true);

            return $this->redirectToRoute('app_destination_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('destination/new.html.twig', [
            'destination' => $destination,
            'form' => $form,
        ]);
    }

    #[Route('/{destination}', name: 'app_destination_show', methods: ['GET', 'POST'])]
    public function show(ManagerRegistry $doctrine, Request $request, ReviewRepository $reviewRepository, Destination $destination): Response
    {
        $review = new Review();
        $review->setUser($this->getUser());
        $review->setDestination($destination);
        $form = $this->createForm(ReviewType::class, $review);
        $form->handleRequest($request);
        $em = $doctrine->getManager();
        $userList = $em->getRepository(User::class)->findAll();
        $reviewList = $em->getRepository(Review::class)->findAll();
        $typeList = $em->getRepository(Type::class)->findAll();
        if ($form->isSubmitted() && $form->isValid()) {
            $reviewRepository->save($review, true);
            return $this->redirect($request->getUri());
        }

        return $this->renderForm('destination/show.html.twig', [
            'destination' => $destination,
            'form' => $form,
            'userList' => $userList,
            'reviewList' => $reviewList,
            'typeList' => $typeList,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_destination_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Destination $destination, DestinationRepository $destinationRepository): Response
    {
        $form = $this->createForm(DestinationType::class, $destination);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $destinationRepository->save($destination, true);

            return $this->redirectToRoute('app_destination_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('destination/edit.html.twig', [
            'destination' => $destination,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_destination_delete', methods: ['POST'])]
    public function delete(Request $request, Destination $destination, DestinationRepository $destinationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $destination->getId(), $request->request->get('_token'))) {
            $destinationRepository->remove($destination, true);
        }

        return $this->redirectToRoute('app_destination_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/', name: 'app_filter', methods: ['GET'])]
    public function filter(DestinationRepository $destinationRepository, TypeRepository $typeRepository, string $filter, Request $request): Response
    {
        $filter = $request->get('filter');
        return $this->render('destination/index.html.twig', [
            'destinations' => $destinationRepository->findAll(),
            'typeList' => $typeRepository->findAll(),
            'filter' => $filter,
        ]);
    }
}

TP_vacances/templates/destination/_delete_form.html.twig
<form method="post" action="{{ path('app_destination_delete', {'id': destination.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ destination.id) }}">
    <button class="btn">Delete</button>
</form>

TP_vacances/templates/destination/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

TP_vacances/templates/destination/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Destination{% endblock %}

{% block body %}
    <h1>Edit Destination</h1>

    {{ include('destination/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_destination_index') }}">back to list</a>

    {{ include('destination/_delete_form.html.twig') }}
{% endblock %}

TP_vacances/templates/destination/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Destination index{% endblock %}

{% block body %}
    <div>
        <a href="{{ path('app_home') }}">Accueil</a>
    </div>
    <div class="d-flex justify-content-center mt-3">
        <form class="col-12 d-flex justify-content-around border border-1 border-light rounded p-2 bg-dark"
              action="{{ path('app_filter') }}">
            <div class="row align-content-center justify-content-center">
                <label for="filter"> Sélectionner le type de voyage :</label>
            </div>
            <div>
                <select class="form-select" id="filter" name="filter">
                    {% for type in typeList %}
                        <option value="{{ type.id }}">{{ type.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <select class="form-select" id="filter" name="pays">
                    <option>-- Tous les pays --</option>
                    {% for destination in destination %}
                        <option value="{{ destination.country }}">{{ destination.country }}</option>
                    {% endfor %}
                </select>
            </div>
            <div>
                <button class="btn btn-outline-light" type="submit">Filtrer</button>
            </div>
        </form>
    </div>
    {% if text is defined %}
        <p>{{ text }}</p>
    {% endif %}
    <div class="row justify-content-around">
        {% for destination in pagination %}
            <div class="col-4 mt-4">
                <div class="card border border-2 border-dark  h-100">
                    <img class="card-img-top" src="{{ destination.image }}" alt="Card image cap">
                    <div class="card-body">
                        <h4 class="card-title">{{ destination.name }}</h4>
                        <h5 class="card-title">{{ destination.country }}</h5>
                        <p class="card-text">{{ destination.description|length > 60 ? destination.description|slice(0, 60) ~ '...' : destination.description }}</p>
                    </div>
                    <div class="card-footer">
                        <a class="btn btn-dark"
                           href="{{ path('app_destination_show', {'destination': destination.id}) }}">Découvrir</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="d-flex justify-content-center mt-4">
        {{ knp_pagination_render(pagination) }}
    </div>
    {% if app.user %}
        <a href="{{ path('app_destination_new') }}">NOUVELLE DESTINATION</a>
    {% endif %}
{% endblock %}

TP_vacances/templates/destination/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Destination{% endblock %}

{% block body %}
    <h1>Nouvelle destination</h1>

    {% form_theme form 'bootstrap_5_layout.html.twig' %}

    {{ include('destination/_form.html.twig') }}

    <a href="{{ path('app_destination_index') }}">back to list</a>
{% endblock %}

TP_vacances/templates/destination/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Destination{% endblock %}

{% block body %}
    <div class="m-3">
        <p><a href="{{ path('app_home') }}">Accueil</a>
            ->
            <a href="{{ path('app_destination_index') }}">Destinations</a>
            ->
            {{ destination.name }}
        </p>
    </div>


    <div class="m-3 border border-2 rounded border-dark">
        <div>
            <img class="card-img-top" src="{{ destination.image }}" alt="Card image cap">
        </div>
        <div class="d-flex justify-content-between p-2">
            <div>
                <h1 class="card-title">{{ destination.name }}</h1>
                <h2 class="card-title">{{ destination.country }}</h2>
            </div>
            <div>
                {% for type in typeList %}
                    {% if type.id == destination.type.id %}
                        <h4>{{ type.name }}</h4>
                    {% endif %}
                {% endfor %}
                <h4>Note : {{ moyenne_review(destination)|round(2, 'floor') }}/5</h4>
            </div>
        </div>
        <div class="p-2">
            <div>
                <h6>Description :</h6>
                <p class="card-text">{{ destination.description }}</p>
            </div>
        </div>
    </div>

    {% form_theme form 'bootstrap_5_layout.html.twig' %}
    <div class="m-3 border border-2 rounded border-dark p-2">
        {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-dark">{{ button_label|default('Save') }}</button>
        {{ form_end(form) }}
    </div>

    {% for review in reviewList %}
        {% if review.destination.id == destination.id %}
            <div class="m-3 border border-2 rounded border-dark p-2">
                <p>{{ review.content }}</p>
                <p>{{ review.notation }} / 5 </p>
                <div class="d-flex justify-content-between">
                    <div class="d-flex flex-row align-items-center">
                        {# <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(4).webp" alt="avatar" width="25"
                                         height="25" /> #}
                        {% for user in userList %}
                            {% if review.user.id == user.id %}
                                <a href="{{ path('app_profile', {'user': user.id}) }}"
                                   class="small mb-0 ms-2">{{ user.username }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}
{% endblock %}